#ifndef CONSTANTS_H
#define CONSTANTS_H


#define BALL_TILE_INDEX 0x1
#define PADDLE_EDGE_TILE_INDEX 0x2
#define PADDLE_MIDDLE_TILE_INDEX 0x3

#define BALL_PALETTE 0x0
#define PADDLE_PALETTE 0x1

#define BALL_OAM 0x0
#define PADDLE_0_OAM 0x1
#define PADDLE_1_OAM 0x2
#define PADDLE_2_OAM 0x3

#define SPRITE_FLIP_H 0b00100000

#endif